groups:
- name: main
  jobs:
  - package
  - deploy-app

resource_types:
- name: azure-blob
  type: docker-image
  source:
    repository: cfcloudops/azure-blobstore-concourse-resource

#- name: http-api
#  type: docker-image
#  source:
#   repository: aequitas/http-api-resource
#   tag: latest

resources:
#- name: hipchat
#  type: http-api
#  source:
#          uri: https://projecteagle.hipchat.com/v2/room/3318095/notification
#          method: POST
#          headers:
#              Authorization: "Bearer {hipchat_token}"
#          json:
#              color: "{color}"
#              message: "Build {BUILD_PIPELINE_NAME}{BUILD_JOB_NAME}, nr: {BUILD_NAME} {message}!"
#          hipchat_token: {{HIPCHAT_TOKEN}}


- name: SpringBootExample
  type: git
  source:
    branch: master
    uri: https://github.com/dev-dksc103334/SpringBootExample.git 

- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

- name: azure-blobstore
  type: azure-blob
  source:
    container: {{azure-cont}} 
    storage_account_name: {{storage_account_name}}
    storage_access_key: {{storage_access_key}}
    #regexp: demo-([0-9\.]+)-([\w]+).jar
    regexp: springBootDemo-([0-9\.]+).tar.gz 
    environment: AzureCloud
    #versioned_file: demo-0.0.1-SNAPSHOT.jar


jobs:
- name: package
  plan:
  - get: SpringBootExample
    trigger: true
  - task: package
    privileged: true
    #file: SpringBootExample/ci/tasks/package.yml
    config:
       platform: linux
       image_resource:
          type: docker-image
          source:
             repository: maven
             tag: latest
       inputs:
          - name: SpringBootExample
       outputs:
          - name: target
       run:
#          path: "mvn"
#          args: ["-f", "SpringBootExample/test-api-master/pom.xml", "-Dmaven.test.skip=true", "package"]
          path: sh
          args:
          - -exc
          - |
           mvn -f SpringBootExample/test-api-master/pom.xml package
           pwd
           cd SpringBootExample/test-api-master/
           tar -czf springBootDemo-0.0.1.tar.gz target/demo-*.jar manifest.yml 
           mv springBootDemo-*.gz ../../target/
       params:
          MAVEN_BASEDIR: SpringBootExample/test-api-master
  - put: azure-blobstore
    params: { file: ./target/springBootDemo-0.0.1.tar.gz }
#  on_success:
#              put: hipchat
#              params:
#                    color: green
#                    message: was a success
#  on_failure:
#              put: hipchat
##              params:
#                    color: red
#                    message: failed horribly     

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: azure-blobstore
    trigger: true
    passed: 
    - package
  - task: deploy-cf 
    privileged: true
    config: 
      platform: linux
      image_resource:
         type: docker-image
         source:
           repository: alpine
           tag: latest

      inputs:
      - name: azure-blobstore 
      outputs:
      - name: spb-app 

      run:
       path: sh
       args:
       - -exc
       - |
         mkdir -p spb-app/target
         cd spb-app
         tar -xzf ../azure-blobstore/springBootDemo-0.0.1.tar.gz
         find .

  - put: PWS
    params:
      manifest: spb-app/manifest.yml


- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: SpringBootExample
    trigger: true
# - task: email-notification-failure
#      file: <your-resource-directory-location-goes-here>/send-email.yml
#      params:
#        SMTP_HOST: <<your-smtp-host-goes-here  e.g. smtp.gmail.com>
#        SMTP_PORT: <<your-smtp-server-port-number  e.g. 465>
#        SMTP_USERNAME: <<your-email-id-with-encoded-@-sign  e.g. myemail%40gmai.com >
#        SMTP_PASSWORD: <your-email-password>
#        EMAIL_FROM: <the-sender-email-address-without-enconding   e.g. myemail@gmail.com>
#        EMAIL_TO: <the-list-of-comma-separated-destination-emails-without-encoding  e.g. him@there.com,her@here.net>
#        EMAIL_SUBJECT_TEXT: <email-subject-message   e.g. Hello there>
#        EMAIL_BODY_TEXT: <email-body-text   e.g. This is my email body.>
#        EMAIL_ATTACHMENTS: <json-array-with-attachments-info. See format below. Omit this field if no attachment is needed>
