groups:
- name: main
  jobs:
  - package
  - deploy-app

resource_types:
- name: azure-blob
  type: docker-image
  source:
    repository: cfcloudops/azure-blobstore-concourse-resource

resources:
- name: SpringBootExample
  type: git
  source:
    branch: master
    uri: https://github.com/dev-dksc103334/SpringBootExample.git 

- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

- name: azure-blobstore
  type: azure-blob
  source:
    container: {{azure-cont}} 
    storage_account_name: {{storage_account_name}}
    storage_access_key: {{storage_access_key}}
    regexp: demo-([0-9\.]+)-([\w]+).jar
    environment: AzureCloud
    #versioned_file: demo-0.0.1-SNAPSHOT.jar


jobs:
- name: package
  plan:
  - get: SpringBootExample
    trigger: true
  - task: package
    privileged: true
    #file: SpringBootExample/ci/tasks/package.yml
    config:
       platform: linux
       image_resource:
          type: docker-image
          source:
             repository: maven
             tag: latest
       inputs:
          - name: SpringBootExample
       outputs:
          - name: target
       run:
#          path: "mvn"
#          args: ["-f", "SpringBootExample/test-api-master/pom.xml", "-Dmaven.test.skip=true", "package"]
          path: sh
          args:
          - -exc
          - |
           mvn -f SpringBootExample/test-api-master/pom.xml package
           pwd
           mv SpringBootExample/test-api-master/target/demo-*.jar target/
       params:
          MAVEN_BASEDIR: SpringBootExample/test-api-master
  - put: azure-blobstore
    params: { file: ./target/demo-0.0.1-SNAPSHOT.jar }

- name: deploy-app
  serial: true
  public: true
  plan:
  - get: azure-blobstore
  - get: SpringBootExample 
    trigger: true
    passed: 
    - package
  - task: deploy-cf 
    privileged: true
    #file: SpringBootExample/ci/tasks/jarfile.yml 
    config: 
      platform: linux
      image_resource:
         type: docker-image
         source:
           repository: alpine
           tag: latest

      inputs:
      - name: azure-blobstore 
      - name: SpringBootExample
     #  path: test-api-master
      outputs:
      - name: spb-app 

      run:
       path: sh
       args:
       - -exc
       - |
         find .
         pwd
         cp -pr SpringBootExample/test-api-master spb-app/
         mkdir -p spb-app/test-api-master/target
         cp ./azure-blobstore/demo-0.0.1-SNAPSHOT.jar spb-app/test-api-master/target/
  - put: PWS
    params:
      manifest: spb-app/test-api-master/manifest.yml


- name: promote-new-version
  serial: true
  public: true
  plan:
  - get: SpringBootExample
    trigger: true
# - task: email-notification-failure
#      file: <your-resource-directory-location-goes-here>/send-email.yml
#      params:
#        SMTP_HOST: <<your-smtp-host-goes-here  e.g. smtp.gmail.com>
#        SMTP_PORT: <<your-smtp-server-port-number  e.g. 465>
#        SMTP_USERNAME: <<your-email-id-with-encoded-@-sign  e.g. myemail%40gmai.com >
#        SMTP_PASSWORD: <your-email-password>
#        EMAIL_FROM: <the-sender-email-address-without-enconding   e.g. myemail@gmail.com>
#        EMAIL_TO: <the-list-of-comma-separated-destination-emails-without-encoding  e.g. him@there.com,her@here.net>
#        EMAIL_SUBJECT_TEXT: <email-subject-message   e.g. Hello there>
#        EMAIL_BODY_TEXT: <email-body-text   e.g. This is my email body.>
#        EMAIL_ATTACHMENTS: <json-array-with-attachments-info. See format below. Omit this field if no attachment is needed>
